"""
Localization Manager for Mini-Game-Sammlung.
Supports German (de) and English (en).
"""
import sys
import ctypes

def get_system_language():
    try:
        if sys.platform == "win32":
            windll = ctypes.windll.kernel32
            lang_id = windll.GetUserDefaultUILanguage()
            primary_lang = lang_id & 0x3ff
            if primary_lang == 0x07: # German
                return "de"
        return "en"
    except Exception:
        return "en"

_current_language = get_system_language()

def set_language(lang):
    global _current_language
    if lang in TRANSLATIONS:
        _current_language = lang

def get_language():
    return _current_language

def get_text(key, **kwargs):
    lang_dict = TRANSLATIONS.get(_current_language, TRANSLATIONS["en"])
    text = lang_dict.get(key, key)
    if kwargs:
        try:
            return text.format(**kwargs)
        except Exception:
            return text
    return text

TRANSLATIONS = {
    "de": {
        "game_mole_master": "Maulwurf-Meister",
        "game_mole_master_desc": "Höre genau, aus welcher Richtung der Maulwurf kommt, und drücke die entsprechende Pfeiltaste.",
        "game_mole_master_instructions": "Hörst du den Klick links, drücke Pfeil Links. Oben, Pfeil Oben, etc. Sei schnell!",
        "game_rhythm_master": "Rhythmus-König",
        "game_rhythm_master_desc": "Drücke die Leertaste genau im Takt des Metronoms. Werde zum Rhythmus-König!",
        "game_rhythm_master_instructions": "Höre auf den Takt. Drücke Leertaste oder Enter genau dann, wenn du den Klick hörst. Die Geschwindigkeit nimmt zu!",
        "app_title": "Mini-Game-Sammlung v1.5",
        "welcome": "Willkommen bei der Mini-Game-Sammlung!",
        "ready": "Mini-Game-Sammlung bereit. Hauptmenü.",
        "main_menu": "Hauptmenü",
        "play": "Spielen",
        "highscores": "Ranglisten",
        "settings": "Einstellungen",
        "language": "Sprache",
        "exit": "Beenden",
        "back": "Zurück",
        "cat_action": "Action",
        "cat_logic": "Logik",
        "cat_nav": "Navigation",
        "cat_speech": "Sprache",
        "cat_sim": "Simulation",
        "cat_all": "Alle Spiele",
        "game_echo_hunter": "Echo-Jäger",
        "game_echo_hunter_desc": "Finde das unsichtbare Ziel mithilfe von Echos.",
        "game_echo_hunter_instructions": "Höre auf den Piep-Ton. Bewege dich mit den Pfeiltasten. Der Ton wird schneller und höher, wenn du näher kommst.",
        "select_category": "Wähle eine Kategorie",
        "select_game": "Wähle ein Spiel",
        "highscore_for": "Rangliste für {game}",
        "highscore_category": "Rangliste: {cat}",
        "no_highscores": "Noch keine Highscores vorhanden.",
        "no_highscores_in_category": "In dieser Kategorie gibt es noch keine Highscores.",
        "points": "Punkte",
        "game_over": "Spiel vorbei!",
        "final_score": "Dein Endstand: {score} Punkte.",
        "new_highscore": "Neuer Rekord!",
        "instructions": "Anleitung",
        "instructions_base": "Drücke ESC zum Beenden.",
        "input_empty_error": "Eingabe darf nicht leer sein.",
        "input_cleared": "Leer",
        "already_revealed": "Schon aufgedeckt",
        "pair_found": "Paar gefunden!",
        "no_pair": "Kein Paar",
        "safe_open": "Tresor offen!",
        "try_again": "Falsch, probier es nochmal.",
        "mic_found": "Gefunden! Das Goldene Mikrofon gehört dir!",
        "crash": "Crash!",
        "farm_found": "Gefunden! Du hast das Tier gefunden!",
        "wall": "Wand",
        "goal_reached": "Ziel erreicht!",
        "hit_obstacle": "Getroffen!",
        "grid_field": "Feld {pos}",
        "grid_field_revealed": "Feld {pos}: {item} (gelöst)",
        "number_locked": "Zahl {idx} eingerastet.",
        "letters_shuffled": "Buchstaben: {letters}",
        "distance_feedback": "Du warst {dist} Meter entfernt.",
        "position_feedback": "Position {x}, {y}",
        "default_player_name": "Spieler",
        "game_audio_sequence": "Sound-Folge",
        "game_audio_sequence_desc": "Merke dir die Reihenfolge der Geräusche und wiederhole sie.",
        "game_audio_sequence_instructions": "Ich spiele dir eine Folge von Geräuschen vor. Wiederhole sie mit den Pfeiltasten: Oben, Unten, Links, Rechts.",
        "simon_listen": "Hör genau zu...",
        "simon_your_turn": "Du bist dran!",
        "simon_up": "Oben",
        "simon_down": "Unten",
        "simon_left": "Links",
        "simon_right": "Rechts",
        "wrong": "Falsch!",
        
        # Sound Quiz Options
        "sq_mouse": "Maus",
        "sq_car": "Auto",
        "sq_piano": "Klavier",
        "sq_bell": "Klingel",
        "sq_bird": "Vogel",
        "sq_thunder": "Donner",
        "sq_dog": "Hund",
        "sq_alarm": "Alarm",
        "sq_water": "Wasser",
        
        # Letter Salad Words
        "ls_word1": "Audio",
        "ls_word2": "Studio",
        "ls_word3": "Tycoon",
        "ls_word4": "Blind",
        "ls_word5": "Spiel",
        
        # Capital Hunter Options
        "ch_berlin": "Berlin",
        "ch_vienna": "Wien",
        "ch_bern": "Bern",
        "ch_london": "London",
        "ch_paris": "Paris",
        "ch_rome": "Rom",
        "ch_madrid": "Madrid",
        "ch_milan": "Mailand",
        
        # Game Instructions
        "game_sound_memo_instructions": "Finde die Pärchen. Nutze die Pfeiltasten zum Navigieren und Enter zum Aufdecken.",
        "game_safe_cracker_instructions": "Finde die 3 Zahlen der Kombination. Drehe mit Pfeil links/rechts.",
        "game_letter_salad_instructions": "Buchstabensalat! Errate das Wort. Ich lese die Buchstaben durcheinander vor.",
        "game_golden_mic_instructions": "Finde das Goldene Mikrofon. Nutze die Pfeiltasten. Der Ton wird höher, je näher du kommst.",
        "game_echolot_instructions": "Drücke Enter für einen Ping. Schätze die Distanz zur Wand. Drücke Leertaste, wenn du glaubst, 5 Meter davor zu sein.",
        "game_blind_farm_instructions": "Finde die goldene Schatzkiste in der Scheune! Nutze Pfeiltasten zum Suchen, Enter zum Öffnen.",
        "game_audio_maze_instructions": "Finde den Ausgang. Windgeräusch bedeutet Wand. Pfeiltasten.",
        "game_stereo_catch_instructions": "Das Geräusch bewegt sich links und rechts. Drücke Enter, wenn es genau in der Mitte ist!",
        "game_space_flight_instructions": "Weiche Asteroiden aus! Hörst du sie links, drücke Rechts. Hörst du sie rechts, drücke Links.",
        "game_beat_reaktor_instructions": "Drücke Enter, wenn du den Ton hörst. Sei präzise!",
        "game_math_blitz_instructions": "Löse die Rechenaufgaben so schnell wie möglich!",
        "game_key_storm_instructions": "Hämmer auf die Tasten, die ich dir sage! Du hast 20 Sekunden Zeit.",
        "game_capital_hunter_instructions": "Ein Quiz über Hauptstädte. Drücke 1, 2 oder 3 für die richtige Antwort.",
        "game_audio_bowling_instructions": "Audio-Bowling! Drücke die Leertaste zum Werfen, wenn das Schwingen am lautesten ist.",
        "game_rps_extreme_instructions": "Schere, Stein, Papier! Drücke 1 für Schere, 2 für Stein, 3 für Papier.",
        "game_simon_says_instructions": "Merke dir die Ton-Reihenfolge und wiederhole sie mit den Pfeiltasten.",
        "game_number_guess_instructions": "Errate eine Zahl zwischen 1 und 100. Nutze die Pfeiltasten zum Einstellen und Enter zum Bestätigen.",
        "game_bomb_defuser_instructions": "Entschärfe die Bombe! Drücke Enter im letzten Moment, bevor sie explodiert.",
        "game_reaction_blitz_instructions": "Reaktions-Blitz! Drücke eine beliebige Taste, sobald du den Blitz-Ton hörst. Sei so schnell wie möglich!",
        "round_number": "Runde {idx}",
        "too_slow": "Zu langsam!",
        "too_early": "Zu früh!",
        "reaction_result": "{ms} Millisekunden!",
        "wait_for_it": "Warten...",
        "good": "Gut!",
        
        # Keys
        "key_up": "Oben",
        "key_down": "Unten",
        "key_left": "Links",
        "key_right": "Rechts",
        "key_space": "Leertaste",
        
        # Categories
        "cat_action": "Action & Reaktion",
        "cat_logic": "Logik & Gedächtnis",
        "cat_nav": "Navigation & Erkundung",
        "cat_speech": "Sprache & Wissen",
        "cat_sim": "Simulation & Spaß",
        "cat_misc": "Verschiedenes",
        
        # Game Names & Descs
        "game_beat_reaktor": "Beat-Reaktor",
        "game_beat_reaktor_desc": "Drücke die Leertaste genau dann, wenn du das Becken hörst. Trainiere deine Reflexe!",
        "game_stereo_catch": "Stereo-Münzfang",
        "game_stereo_catch_desc": "Ein Geräusch wandert von links nach rechts. Schnapp es dir genau in der Mitte.",
        "game_bomb_defuser": "Bomben-Entschärfer",
        "game_bomb_defuser_desc": "Das Ticken wird immer schneller. Entschärfe die Bombe im letzten Moment!",
        "game_key_storm": "Tasten-Gewitter",
        "game_key_storm_desc": "Drücke so schnell wie möglich die angesagten Tasten innerhalb der Zeit.",
        "game_sound_memo": "Sound-Memo",
        "game_sound_memo_desc": "Finde die passenden Geräusch-Paare in einem versteckten Gitter.",
        "game_simon_says": "Simon Says",
        "game_simon_says_desc": "Merke dir die Ton-Reihenfolge und wiederhole sie.",
        "game_number_guess": "Zahlen-Raten",
        "game_number_guess_desc": "Errate eine Zahl zwischen 1 und 100.",
        "game_safe_cracker": "Tresor-Knacker",
        "game_safe_cracker_desc": "Drehe das Schloss und höre auf die Klicks.",
        "game_math_blitz": "Mathe-Blitz",
        "game_math_blitz_desc": "Löse so viele Rechenaufgaben wie möglich unter Zeitdruck.",
        
        "game_golden_mic": "Das Goldene Mikrofon",
        "game_golden_mic_desc": "Suche das Mikrofon im Raum. Der Ton zeigt dir, ob du nah dran bist.",
        "game_audio_maze": "Audio-Labyrinth",
        "game_audio_maze_desc": "Finde den Weg aus dem Labyrinth nur mit Hilfe von Klängen.",
        "game_echolot": "Echolot",
        "game_echolot_desc": "Schätze die Entfernung zur Wand anhand des Echos deines Pings.",
        "game_blind_farm": "Die blinde Farm",
        "game_blind_farm_desc": "Suche ein ganz bestimmtes Tiergeräusch in einem Feld voller Tiere.",
        "game_space_flight": "Weltraum-Flug",
        "game_space_flight_desc": "Weiche Asteroiden aus, indem du in die entgegengesetzte Richtung lenkst.",
        
        "game_word_snake": "Wort-Schlange",
        "game_word_snake_desc": "Bilde eine Kette aus Wörtern. Das neue Wort muss mit dem Endbuchstaben des alten beginnen.",
        "game_sound_quiz": "Geräusche-Quiz",
        "game_sound_quiz_desc": "Erkennst du, was das für ein Geräusch war? Wähle aus drei Möglichkeiten.",
        "game_letter_salad": "Buchstaben-Salat",
        "game_letter_salad_desc": "Ich nenne dir Buchstaben durcheinander. Welches Wort ergibt das?",
        "game_capital_hunter": "Hauptstadt-Jäger",
        "game_capital_hunter_desc": "Ein Quiz über die Hauptstädte dieser Welt. Kennst du sie alle?",
        
        "game_audio_bowling": "Audio-Bowling",
        "game_audio_bowling_desc": "Wirf die Kugel, wenn der Schwung am höchsten ist, um alle Pins abzuräumen.",
        "game_rps_extreme": "Schere, Stein, Papier Extreme",
        "game_rps_extreme_desc": "Der Klassiker gegen die KI mit dramatischen Soundeffekten.",
        "game_reaction_blitz": "Reaktions-Blitz",
        "game_reaction_blitz_desc": "Teste deine Reflexe! Reagiere sofort auf den Ton.",
        "game_audio_archery": "Audio-Bogenschießen",
        "game_audio_archery_desc": "Schieße den Pfeil genau in die Mitte des Ziels.",
        "game_audio_slots": "Audio-Slots",
        "game_audio_slots_desc": "Versuche drei gleiche Sounds in einer Reihe zu bekommen!",
        "game_audio_slots_instructions": "Drücke Enter, um die Walzen zu drehen. Drücke erneut Enter (oder warte), um sie nacheinander zu stoppen. Drei gleiche Sounds bringen den Jackpot!",
        "game_audio_archery_instructions": "Ein Ton bewegt sich von links nach rechts. Drücke die Leertaste genau dann, wenn der Ton perfekt in der Mitte ist, um ins Goldene zu treffen!",
        "game_math_blitz_instr": "Löse so viele Rechenaufgaben wie möglich unter Zeitdruck.",
        "game_math_blitz_instr": "Löse so viele Rechenaufgaben wie möglich unter Zeitdruck.",
        "math_plus": "plus",
        "math_minus": "minus",
        "math_times": "mal",
        "game_sound_memo_instructions": "Finde die passenden Geräusch-Paare. Nutze die Pfeiltasten zum Navigieren und Enter zum Aufdecken.",
        "game_safe_cracker_instructions": "Finde die 3 Zahlen der Kombination. Drehe mit Pfeil links/rechts.",
        "game_letter_salad_instructions": "Buchstabensalat! Errate das Wort. Ich lese dir die Buchstaben gemischt vor.",
        "game_golden_mic_instructions": "Suche das goldene Mikrofon. Nutze die Pfeiltasten. Der Ton wird höher, je näher du kommst.",
        "game_echolot_instructions": "Drücke Enter für einen Ping. Schätze die Entfernung zur Wand. Drücke Leertaste, wenn du glaubst, 5 Meter davor zu sein.",
        "game_blind_farm_instructions": "Finde die goldene Schatzkiste in der Scheune! Nutze Pfeiltasten zum Suchen, Enter zum Öffnen.",
        "game_audio_maze_instructions": "Finde den Ausgang. Windgeräusch bedeutet Wand. Pfeiltasten.",
        "game_stereo_catch_instructions": "Das Geräusch wandert links und rechts. Drücke Enter, wenn es genau in der Mitte ist!",
        "game_space_flight_instructions": "Weiche Asteroiden aus! Hörst du sie links, drücke Rechts. Hörst du sie rechts, drücke Links.",
        "game_beat_reaktor_instructions": "Drücke Enter, wenn du das Geräusch hörst. Sei präzise!",
        "game_math_blitz_instructions": "Löse die Matheaufgaben so schnell wie möglich!",
        "game_word_snake_instructions": "Wortschlange! Ich nenne ein Wort, du tippst eines, das mit dem letzten Buchstaben beginnt.",
        "game_sound_quiz_instructions": "Erkenne das Geräusch! Drücke 1, 2 oder 3 für die richtige Antwort.",
        "game_capital_hunter_instructions": "Ein Quiz über die Hauptstädte der Welt. Drücke 1, 2 oder 3 für die richtige Antwort.",
        "game_audio_bowling_instructions": "Audio-Bowling! Drücke Leertaste zum Werfen, wenn das Schwingen am lautesten ist.",
        "game_rps_extreme_instructions": "Schere, Stein, Papier! Drücke 1 für Schere, 2 für Stein, 3 für Papier.",
        "game_simon_says_instructions": "Merke dir die Ton-Reihenfolge und wiederhole sie mit den Pfeiltasten.",
        "game_number_guess_instructions": "Errate eine Zahl zwischen 1 und 100. Nutze Pfeil hoch/runter zum Einstellen und Enter zum Bestätigen.",
        "game_bomb_defuser_instructions": "Entschärfe die Bombe! Drücke Leertaste im letzten Moment, bevor sie explodiert.",
        "game_key_storm_instructions": "Hämmere auf die Tasten die ich dir nenne! Du hast 20 Sekunden Zeit.",
        "higher": "Höher",
        "lower": "Tiefer",
        "correct_number": "Richtig! Die Zahl war {number}. Du hast {tries} Versuche gebraucht.",
        "simon_up": "Oben",
        "simon_down": "Unten",
        "simon_left": "Links",
        "simon_right": "Rechts",
        "bomb_defused": "Bombe entschärft! Du hast {points} Punkte bekommen.",
        "bomb_exploded": "BOOM! Zu spät.",
        "bomb_defused_simple": "Entschärft!",
        "bomb_too_early": "Zu früh!",
        "rps_scissors": "Schere",
        "rps_stone": "Stein",
        "rps_paper": "Papier",
        "rps_ai_has": "Ich habe {choice}.",
        "rps_draw": "Unentschieden!",
        "rps_win": "Du gewinnst!",
        "rps_lose": "Ich gewinne!",
        "rps_choose": "Wähle dein Symbol!",
        "cap_germany": "Deutschland",
        "cap_france": "Frankreich",
        "cap_italy": "Italien",
        "cap_country": "Land: {country}.",
        "bowl_pins": "Du hast {pins} Pins umgeworfen!",
        "simon_listen": "Hör zu.",
        "simon_your_turn": "Du bist dran.",
        "wrong": "Falsch!",
        "settings_sfx_vol": "Sfx Lautstärke: {vol}%",
        "settings_music_vol": "Musik Lautstärke: {vol}%",
        "settings_speech_rate": "Sprach-Geschwindigkeit: {rate}%",
        "settings_lang": "Sprache: {lang}",
        "player_count_title": "Spieleranzahl für {game}",
        "player_count_item": "{count} Spieler",
        "name_input_prompt": "Name für Spieler {idx}:",
        "aborted_main_menu": "Abgebrochen. Hauptmenü.",
        "game_desc_start": "Beschreibung: {desc}. Drücke Enter zum Starten oder ESC zum Abbrechen.",
        "first_player": "Erster Spieler: {player}",
        "round_ended_next_player": "Runde beendet. Nächster Spieler: {player}. Drücke Enter, wenn du bereit bist.",
        "all_players_finished": "Alle Spieler sind fertig. Zurück zum Hauptmenü.",
        "games_in_category": "Spiele in {cat}",
        "no_desc_available": "Keine Beschreibung verfügbar.",
        "input_empty_error": "Eingabe darf nicht leer sein.",
        "input_cleared": "Leer",
        "settings_speech_vol": "Sprach-Lautstärke: {vol}%",
        "score_entry": "{idx}. {name}: {score} Punkte",
        "category_rank_entry": "{idx}. {name}: {score} Pkt. ({game})",
        "hit": "Treffer!",
        "hit_perfect": "Perfekt!",
        "hit_good": "Gut gemacht!",
        "hit_ok": "Knapp!",
        "miss": "Daneben!",
        "too_late": "Zu spät!",
        "too_early": "Zu früh!",
        "game_word_snake_instructions": "Wortschlange! Ich nenne ein Wort, du tippst eines, das mit dem letzten Buchstaben beginnt.",
        "game_sound_quiz_instructions": "Erkenne das Geräusch! Drücke 1, 2 oder 3 für die richtige Antwort.",
        "word_snake_start": "Startwort: {word}",
        "word_snake_next": "Nächstes Wort! Letzter Buchstabe: {char}",
        "word_snake_wrong": "Falsch! Muss mit {char} beginnen.",
        "sound_quiz_question": "Was ist das? 1: {opt1}, 2: {opt2}, 3: {opt3}",
        "language_changed": "Sprache auf Deutsch gestellt.",
        "time_up": "Zeit abgelaufen!",
        "press_enter_to_start": "Drücke Enter zum Starten.",
        "what_is": "Was ist {a} {op} {b}?",
        "farm_item_1": "Altes Eisenrohr",
        "farm_item_2": "Holzkiste",
        "farm_item_3": "Blecheimer",
        "farm_item_4": "Stoffbeutel",
        "farm_item_5": "Türgriff",
        "farm_item_6": "Glasscherben",
        "farm_item_7": "Schatzkiste",
        "farm_item_8": "Brennholz",
        "farm_item_9": "Glocke",
        "farm_item_10": "Tonkrug",
        "item_number": "Gegenstand {idx}",
        "just_an_item": "Nur ein {item}.",
        "game_code_breaker": "Code-Knacker",
        "game_code_breaker_desc": "Errate die richtige Kombination aus Tönen.",
        "game_code_breaker_instructions": "Finde die 3-stellige Tonfolge. Wähle pro Stelle mit Pfeil hoch/runter den Ton und drücke Enter. Hoher Ton = Richtig, Mittlerer Ton = Falsche Stelle, Tiefer Ton = Nicht dabei.",
        "game_sound_catch": "Ton-Jäger",
        "game_sound_catch_desc": "Fange den Ton, wenn er genau in der Mitte ist.",
        "game_sound_catch_instructions": "Ein Ton wandert zwischen deinen Ohren. Drücke Enter oder Leertaste, wenn er exakt in der Mitte ist.",
        "game_speed_dial": "Schnellwähler",
        "game_speed_dial_desc": "Tippe die angesagten Zahlen so schnell wie möglich.",
        "game_speed_dial_instructions": "Ich sage dir eine Zahlenfolge. Tippe sie so schnell du kannst auf deiner Tastatur ein.",
        "code_breaker_guess": "Kombination prüfen...",
        "code_pos_correct": "Richtig an Stelle {pos}",
        "code_pos_wrong": "Falsche Stelle",
        "code_not_in": "Nicht im Code",
        "speed_dial_next": "Nächste Zahl: {num}",
        "jackpot": "JACKPOT!",
        "slots_spinning": "Walzen drehen sich...",
        "slots_result": "Ergebnis: {r1}, {r2}, {r3}",
        "win_small": "Kleiner Gewinn!",
        "win_big": "Großer Gewinn!",
        "game_audio_slots": "Audio-Slots",
        "game_audio_slots_desc": "Ein virtueller Spielautomat. Versuche dein Glück!",
        "game_audio_slots_instructions": "Drücke Leertaste oder Enter, um die Walzen zu drehen. ESC zum Beenden.",
        "category_rank_entry": "{rank}. {name}: {score} Punkte",
        "games_in_category": "Spiele in Kategorie {cat}",
        
        # New 10 Games
        "game_animal_radar": "Tier-Radar",
        "game_animal_radar_desc": "Finde das Tier im Raum anhand seines Rufes.",
        "game_animal_radar_instructions": "Höre auf den Tierlaut. Nutze die Pfeiltasten, um dich in die Richtung zu drehen. Drücke Enter, wenn du glaubst, das Tier direkt vor dir zu haben.",
        "game_morse_runner": "Morse-Läufer",
        "game_morse_runner_desc": "Entziffere die Morse-Codes so schnell wie möglich.",
        "game_morse_runner_instructions": "Ich spiele einen Morse-Code (kurze und lange Töne). Drücke 1, 2 oder 3 für den richtigen Buchstaben.",
        "game_ticking_clock": "Tickende Uhren",
        "game_ticking_clock_desc": "Finde die Uhr, die aus der Reihe tanzt.",
        "game_ticking_clock_instructions": "Drei Uhren ticken. Eine davon tickt anders. Drücke 1, 2 oder 3, um die falsche Uhr zu wählen.",
        "game_pitch_perfect": "Tonhöhen-Meister",
        "game_pitch_perfect_desc": "Passe deine Tonhöhe an den Zielton an.",
        "game_pitch_perfect_instructions": "Nutze die Pfeiltasten Hoch/Runter, um die Tonhöhe zu ändern. Versuche, genau den Zielton zu treffen.",
        "game_mystery_door": "Geheimnisvolle Türen",
        "game_mystery_door_desc": "Finde die richtige Tür anhand des Echos.",
        "game_mystery_door_instructions": "Drei Türen stehen zur Auswahl. Klopfe an (Pfeiltasten) und höre auf das Echo. Wähle die Tür mit dem speziellen Geräusch.",
        "game_frequency_jammer": "Frequenz-Jäger",
        "game_frequency_jammer_desc": "Suche das Signal im Rauschen.",
        "game_frequency_jammer_instructions": "Drehe am Frequenzrad (Links/Rechts), bis das Rauschen verschwindet und das Signal klar wird.",
        "game_stairs_of_fate": "Treppe des Schicksals",
        "game_stairs_of_fate_desc": "Steige die Treppe hoch, ohne dass sie knarrt.",
        "game_stairs_of_fate_instructions": "Drücke die Pfeiltaste Hoch, um eine Stufe zu steigen. Wenn es knarrt, bleibe sofort stehen (drücke nichts)! Wenn du dich bewegst während es knarrt, fällst du.",
        "game_sound_weaver": "Klang-Weber",
        "game_sound_weaver_desc": "Bringe die Töne der Melodie in die richtige Reihenfolge.",
        "game_sound_weaver_instructions": "Höre dir die Melodie an. Sortiere die Töne mit den Pfeiltasten und Enter um.",
        "game_beat_matcher": "Beat-Matcher",
        "game_beat_matcher_desc": "Triff den Rhythmus perfekt.",
        "game_beat_matcher_instructions": "Drücke die Leertaste genau im Takt des Kicks.",
        "game_audio_balance": "Audio-Balance",
        "game_audio_balance_desc": "Halte den Ton genau in der Mitte.",
        "game_audio_balance_instructions": "Der Ton driftet nach links oder rechts ab. Nutze die Pfeiltasten, um ihn in der Mitte zu halten.",
        
        "beat_synced": "Perfekt synchron!",
        "clock_number": "Uhr {idx}",
        "select_different_clock": "Wähle die Uhr, die anders tickt (1, 2 oder 3).",
        "adjust_pitch_to_match": "Passe deine Tonhöhe an das Ziel an.",
        "find_the_door_with": "Finde die Tür mit dem Geräusch: {sound}.",
        "sound_wind": "Wind",
        "sound_water": "Wasser",
        "sound_fire": "Feuer",
        "door_number": "Tür {idx}",
        "tune_to_clear_signal": "Suche die klare Frequenz.",
        "climb_the_stairs": "Steige die Treppe hinauf. Achtung bei Knarren!",
        "restore_the_melody": "Bringe die Töne in die richtige Reihenfolge.",
        "hit_the_beat": "Drücke die Leertaste genau im Takt!",
        "pan_left": "Nach links!",
        "pan_right": "Nach rechts!",
        "find_the_sound": "Finde das Tier!",
        "radar_distance": "Distanz: {dist} Meter.",
        "door_echo": "Echo",
        "frequency_found": "Sender gefunden!",
        "step_safe": "Sicher",
        "step_creak": "Knarr!",
        "fell_down": "Du bist gefallen!",
        "hit_perfect": "Perfekt!",
        "hit": "Treffer!",
        "morse_a": "Buchstabe A",
        "morse_b": "Buchstabe B",
        "morse_c": "Buchstabe C",
        "morse_d": "Buchstabe D",
        "morse_e": "Buchstabe E",
        "morse_s": "Buchstabe S",
        "morse_o": "Buchstabe O",
        "morse_t": "Buchstabe T"
    },
    "en": {
        "game_mole_master": "Mole Master",
        "game_mole_master_desc": "Listen carefully to the direction the mole is coming from and press the corresponding arrow key.",
        "game_mole_master_instructions": "If you hear the click on the left, press Left Arrow. Up, Up Arrow, etc. Be fast!",
        "game_rhythm_master": "Rhythm King",
        "game_rhythm_master_desc": "Press Space exactly in time with the metronome. Become the Rhythm King!",
        "game_rhythm_master_instructions": "Listen to the beat. Press Space or Enter exactly when you hear the click. The speed increases!",
        "app_title": "Audio Studio Tycoon: Game Pack v1.5",
        "welcome": "Welcome to the Mini-Game Collection!",
        "ready": "Mini-Game Collection ready. Main Menu.",
        "main_menu": "Main Menu",
        "play": "Play",
        "highscores": "Highscores",
        "settings": "Settings",
        "language": "Language",
        "exit": "Exit",
        "back": "Back",
        "cat_action": "Action",
        "cat_logic": "Logic",
        "cat_nav": "Navigation",
        "cat_speech": "Speech",
        "cat_sim": "Simulation",
        "select_category": "Select a category",
        "select_game": "Select a game",
        "highscore_for": "Highscores for {game}",
        "no_highscores": "No highscores available yet.",
        "no_highscores_in_category": "There are no highscores in this category yet.",
        "points": "Points",
        "game_over": "Game Over!",
        "final_score": "Your final score: {score} points.",
        "new_highscore": "New Highscore!",
        "instructions": "Instructions",
        "press_enter_to_start": "Press Enter to start.",
        "player_name_prompt": "Please enter your name",
        "language_changed": "Language set to English.",
        "time_up": "Time's up!",
        "what_is": "What is {a} {op} {b}?",
        "instructions_base": "Press ESC to exit.",
        
        # Keys
        "key_up": "Up",
        "key_down": "Down",
        "key_left": "Left",
        "key_right": "Right",
        "key_space": "Space",
        
        # Categories
        "cat_action": "Action & Reaction",
        "cat_logic": "Logic & Memory",
        "cat_nav": "Navigation & Exploration",
        "cat_speech": "Language & Knowledge",
        "cat_sim": "Simulation & Fun",
        "cat_misc": "Miscellaneous",
        
        # Game Names & Descs
        "game_beat_reaktor": "Beat Reactor",
        "game_beat_reaktor_desc": "Press Space exactly when you hear the cymbal. Train your reflexes!",
        "game_stereo_catch": "Stereo Coin Catch",
        "game_stereo_catch_desc": "A sound moves from left to right. Catch it exactly in the middle.",
        "game_bomb_defuser": "Bomb Defuser",
        "game_bomb_defuser_desc": "The ticking gets faster. Defuse the bomb at the last second!",
        "game_key_storm": "Key Storm",
        "game_key_storm_desc": "Press the announced keys as fast as possible within the time limit.",
        "game_sound_memo": "Sound Memo",
        "game_sound_memo_desc": "Find the matching pairs of sounds in a hidden grid.",
        "game_simon_says": "Simon Says",
        "game_simon_says_desc": "Remember the tone sequence and repeat it.",
        "game_number_guess": "Number Guessing",
        "game_number_guess_desc": "Guess a number between 1 and 100.",
        "game_safe_cracker": "Safe Cracker",
        "game_safe_cracker_desc": "Turn the lock and listen for the clicks.",
        "game_math_blitz": "Math Blitz",
        "game_math_blitz_desc": "Solve as many math problems as possible under time pressure.",
        
        "game_golden_mic": "The Golden Microphone",
        "game_golden_mic_desc": "Find the microphone in the room. The sound shows you if you are close.",
        "game_audio_maze": "Audio Maze",
        "game_audio_maze_desc": "Find your way out of the maze using only sounds.",
        "game_echolot": "Sonar",
        "game_echolot_desc": "Estimate the distance to the wall based on the echo of your ping.",
        "game_blind_farm": "The Blind Farm",
        "game_blind_farm_desc": "Find a specific animal sound in a field full of animals.",
        "game_space_flight": "Space Flight",
        "game_space_flight_desc": "Dodge asteroids by steering in the opposite direction.",
        
        "game_word_snake": "Word Snake",
        "game_word_snake_desc": "Form a chain of words. The new word must start with the last letter of the old one.",
        "game_sound_quiz": "Sound Quiz",
        "game_sound_quiz_desc": "Do you recognize what sound that was? Choose from three options.",
        "game_letter_salad": "Letter Salad",
        "game_letter_salad_desc": "I'll give you letters all mixed up. What word does it make?",
        "game_capital_hunter": "Capital Hunter",
        "game_capital_hunter_desc": "A quiz about the world's capitals. Do you know them all?",
        
        "game_audio_bowling": "Audio Bowling",
        "game_audio_bowling_desc": "Throw the ball when the swing is at its highest to clear all pins.",
        "game_rps_extreme": "Rock, Paper, Scissors Extreme",
        "game_rps_extreme_desc": "The classic against the AI with dramatic sound effects.",
        "game_reaction_blitz": "Reaction Blitz",
        "game_reaction_blitz_desc": "Test your reflexes! React immediately to the sound.",
        "game_audio_archery": "Audio Archery",
        "game_audio_archery_desc": "Shoot the arrow exactly into the center of the target.",
        "game_audio_archery_instructions": "A sound moves from left to right. Press Space exactly when the sound is perfectly in the middle to hit the bullseye!",
        "game_sound_memo_instructions": "Find the matching sound pairs. Use arrow keys to navigate and Enter to reveal.",
        "game_safe_cracker_instructions": "Find the 3 numbers of the combination. Turn with left/right arrows.",
        "game_letter_salad_instructions": "Letter Salad! Guess the word. I'll read the letters mixed up.",
        "game_golden_mic_instructions": "Search for the golden microphone. Use arrow keys. The pitch gets higher as you get closer.",
        "game_echolot_instructions": "Press Enter for a ping. Estimate the distance to the wall. Press Space when you think you're 5 meters away.",
        "game_blind_farm_instructions": "Find the golden treasure chest in the barn! Use arrow keys to search, Enter to open.",
        "game_audio_maze_instructions": "Find the exit. Wind sound means wall. Use arrow keys.",
        "game_stereo_catch_instructions": "The sound moves left and right. Press Enter when it's exactly in the middle!",
        "game_space_flight_instructions": "Dodge asteroids! If you hear them left, press Right. If you hear them right, press Left.",
        "game_beat_reaktor_instructions": "Press Enter when you hear the sound. Be precise!",
        "game_math_blitz_instructions": "Solve the math problems as fast as possible!",
        "game_word_snake_instructions": "Word Snake! I'll say a word, you type one that starts with the last letter.",
        "game_sound_quiz_instructions": "Recognize the sound! Press 1, 2, or 3 for the correct answer.",
        "game_capital_hunter_instructions": "A quiz about world capitals. Press 1, 2, or 3 for the correct answer.",
        "game_audio_bowling_instructions": "Audio Bowling! Press Space to throw when the swinging is loudest.",
        "game_rps_extreme_instructions": "Rock, Paper, Scissors! Press 1 for Scissors, 2 for Rock, 3 for Paper.",
        "game_simon_says_instructions": "Remember the tone sequence and repeat it with the arrow keys.",
        "game_number_guess_instructions": "Guess a number between 1 and 100. Use up/down arrows to adjust and Enter to confirm.",
        "game_bomb_defuser_instructions": "Defuse the bomb! Press Space at the last moment before it explodes.",
        "game_key_storm_instructions": "Hammer the keys I tell you! You have 20 seconds.",
        "math_plus": "plus",
        "math_minus": "minus",
        "math_times": "times",
        "higher": "Higher",
        "lower": "Lower",
        "correct_number": "Correct! The number was {number}. It took you {tries} tries.",
        "simon_up": "Up",
        "simon_down": "Down",
        "simon_left": "Left",
        "simon_right": "Right",
        "bomb_defused": "Bomb defused! You got {points} points.",
        "bomb_exploded": "BOOM! Too late.",
        "bomb_defused_simple": "Defused!",
        "bomb_too_early": "Too early!",
        "rps_scissors": "Scissors",
        "rps_stone": "Stone",
        "rps_paper": "Paper",
        "rps_ai_has": "I have {choice}.",
        "rps_draw": "Draw!",
        "rps_win": "You win!",
        "rps_lose": "I win!",
        "rps_choose": "Choose your symbol!",
        "cap_germany": "Germany",
        "cap_france": "France",
        "cap_italy": "Italy",
        "cap_country": "Country: {country}.",
        "bowl_pins": "You knocked down {pins} pins!",
        "simon_listen": "Listen.",
        "simon_your_turn": "Your turn.",
        "wrong": "Wrong!",
        "settings_sfx_vol": "Sfx Volume: {vol}%",
        "settings_music_vol": "Music Volume: {vol}%",
        "settings_speech_rate": "Speech Rate: {rate}%",
        "settings_lang": "Language: {lang}",
        "player_count_title": "Player count for {game}",
        "player_count_item": "{count} Player",
        "name_input_prompt": "Name for player {idx}:",
        "aborted_main_menu": "Aborted. Main Menu.",
        "input_empty_error": "Input cannot be empty.",
        "input_cleared": "Empty",
        "already_revealed": "Already revealed",
        "pair_found": "Pair found!",
        "no_pair": "No pair",
        "safe_open": "Safe open!",
        "try_again": "Wrong, try again.",
        "mic_found": "Found! The Golden Microphone is yours!",
        "crash": "Crash!",
        "farm_found": "Found! You found the animal!",
        "wall": "Wall",
        "goal_reached": "Goal reached!",
        "hit_obstacle": "Hit!",
        "grid_field": "Field {pos}",
        "grid_field_revealed": "Field {pos}: {item} (solved)",
        "number_locked": "Number {idx} locked.",
        "letters_shuffled": "Letters: {letters}",
        "distance_feedback": "You were {dist} meters away.",
        "position_feedback": "Position {x}, {y}",
        "default_player_name": "Player",
        "game_audio_sequence": "Audio Sequence",
        "game_audio_sequence_desc": "Remember the sequence of sounds and repeat it.",
        "game_audio_sequence_instructions": "I will play a sequence of sounds. Repeat them using the arrow keys: Up, Down, Left, Right.",
        "simon_listen": "Listen carefully...",
        "simon_your_turn": "Your turn!",
        "simon_up": "Up",
        "simon_down": "Down",
        "simon_left": "Left",
        "simon_right": "Right",
        "wrong": "Wrong!",
        
        # Sound Quiz Options
        "sq_mouse": "Mouse",
        "sq_car": "Car",
        "sq_piano": "Piano",
        "sq_bell": "Bell",
        "sq_bird": "Bird",
        "sq_thunder": "Thunder",
        "sq_dog": "Dog",
        "sq_alarm": "Alarm",
        "sq_water": "Water",
        
        # Letter Salad Words
        "ls_word1": "Audio",
        "ls_word2": "Studio",
        "ls_word3": "Tycoon",
        "ls_word4": "Blind",
        "ls_word5": "Game",
        
        # Capital Hunter Options
        "ch_berlin": "Berlin",
        "ch_vienna": "Vienna",
        "ch_bern": "Bern",
        "ch_london": "London",
        "ch_paris": "Paris",
        "ch_rome": "Rome",
        "ch_madrid": "Madrid",
        "ch_milan": "Milan",

        # Game Instructions
        "game_sound_memo_instructions": "Find the pairs. Use the arrow keys to navigate and Enter to reveal.",
        "game_safe_cracker_instructions": "Find the 3 numbers of the combination. Turn with left/right arrows.",
        "game_letter_salad_instructions": "Letter salad! Guess the word. I will read the letters scrambled.",
        "game_golden_mic_instructions": "Find the Golden Microphone. Use the arrow keys. The sound gets higher the closer you get.",
        "game_echolot_instructions": "Press Enter for a ping. Estimate the distance to the wall. Press Space when you think you are 5 meters in front of it.",
        "game_blind_farm_instructions": "Find the golden treasure chest in the barn! Use arrow keys to search, Enter to open.",
        "game_audio_maze_instructions": "Find the exit. Wind sound means wall. Arrow keys.",
        "game_stereo_catch_instructions": "The sound moves left and right. Press Enter when it is exactly in the middle!",
        "game_space_flight_instructions": "Dodge asteroids! If you hear them on the left, press Right. If you hear them on the right, press Left.",
        "game_beat_reaktor_instructions": "Press Enter when you hear the sound. Be precise!",
        "game_math_blitz_instructions": "Solve the math problems as fast as possible!",
        "settings_speech_vol": "Speech Volume: {vol}%",
        "score_entry": "{idx}. {name}: {score} points",
        "hit": "Hit!",
        "hit_perfect": "Perfect!",
        "hit_good": "Good job!",
        "hit_ok": "Close!",
        "miss": "Miss!",
        "game_word_snake_instructions": "Word Snake! I'll name a word, you type one that starts with the last letter.",
        "game_sound_quiz_instructions": "Identify the sound! Press 1, 2, or 3 for the correct answer.",
        "game_capital_hunter_instructions": "A quiz about the world's capitals. Press 1, 2, or 3 for the correct answer.",
        "game_audio_bowling_instructions": "Audio Bowling! Press Space to throw when the swinging is loudest.",
        "game_rps_extreme_instructions": "Rock, Paper, Scissors! Press 1 for Scissors, 2 for Stone, 3 for Paper.",
        "game_simon_says_instructions": "Remember the tone sequence and repeat it with the arrow keys.",
        "game_number_guess_instructions": "Guess a number between 1 and 100. Use arrow keys to adjust and Enter to confirm.",
        "game_bomb_defuser_instructions": "Defuse the bomb! Press Enter at the last moment before it explodes.",
        "game_reaction_blitz_instructions": "Reaction Blitz! Press any key as soon as you hear the lightning sound. Be as fast as possible!",
        "round_number": "Round {idx}",
        "too_slow": "Too slow!",
        "too_early": "Too early!",
        "reaction_result": "{ms} milliseconds!",
        "wait_for_it": "Wait for it...",
        "good": "Good!",
        "game_key_storm_instructions": "Hammer the keys I tell you! You have 20 seconds.",
        "farm_item_1": "Old iron bar",
        "farm_item_2": "Wooden box",
        "farm_item_3": "Tin bucket",
        "farm_item_4": "Cloth bag",
        "farm_item_5": "Door handle",
        "farm_item_6": "Glass shards",
        "farm_item_7": "Treasure chest",
        "farm_item_8": "Firewood",
        "farm_item_9": "Bell",
        "farm_item_10": "Clay pot",
        "word_snake_start": "Starting word: {word}",
        "word_snake_next": "Next word! Last letter: {char}",
        "word_snake_wrong": "Wrong! Must start with {char}.",
        "sound_quiz_question": "What is this? 1: {opt1}, 2: {opt2}, 3: {opt3}",
        "too_late": "Too late!",
        "too_early": "Too early!",
        "all_players_finished": "All players finished. Returning to main menu.",
        "first_player": "First player: {player}",
        "game_desc_start": "Description: {desc}. Press Enter to start or ESC to abort.",
        "games_in_category": "Games in {cat}",
        "no_desc_available": "No description available.",
        "round_ended_next_player": "Round ended. Next player: {player}. Press Enter when you are ready.",
        "item_number": "Item {idx}",
        "just_an_item": "Just a {item}.",
        "game_code_breaker": "Code Breaker",
        "game_code_breaker_desc": "Guess the correct combination of sounds.",
        "game_code_breaker_instructions": "Find the 3-tone sequence. Select a tone for each position using Up/Down and press Enter. High tone = Correct, Medium tone = Wrong position, Low tone = Not in code.",
        "game_sound_catch": "Sound Hunter",
        "game_sound_catch_desc": "Catch the sound when it is exactly in the middle.",
        "game_sound_catch_instructions": "A sound moves between your ears. Press Enter or Space when it is exactly in the middle.",
        "game_speed_dial": "Speed Dial",
        "game_speed_dial_desc": "Type the announced numbers as fast as possible.",
        "game_speed_dial_instructions": "I will tell you a sequence of numbers. Type them as fast as you can on your keyboard.",
        "code_breaker_guess": "Checking combination...",
        "code_pos_correct": "Correct at position {pos}",
        "code_pos_wrong": "Wrong position",
        "code_not_in": "Not in code",
        "speed_dial_next": "Next number: {num}",
        "jackpot": "JACKPOT!",
        "slots_spinning": "Reels are spinning...",
        "slots_result": "Result: {r1}, {r2}, {r3}",
        "win_small": "Small win!",
        "win_big": "Big win!",
        "game_audio_slots": "Audio Slots",
        "game_audio_slots_desc": "A virtual slot machine. Try your luck!",
        "game_audio_slots_instructions": "Press Space or Enter to spin the reels. ESC to exit.",
        "game_echo_hunter": "Echo Hunter",
        "game_echo_hunter_desc": "Find the invisible target using echoes.",
        "game_echo_hunter_instructions": "Listen to the beep. Move with arrow keys. The beep gets faster and higher as you get closer.",
        "player_count_title": "Player count for {game}",
        "player_count_item": "{count} Player(s)",
        "category_rank_entry": "{rank}. {name}: {score} points",
        "game_animal_radar": "Animal Radar",
        "game_animal_radar_desc": "Find the animal in the room based on its call.",
        "game_animal_radar_instructions": "Listen to the animal sound. Use the arrow keys to turn in that direction. Press Enter when you think you have the animal directly in front of you.",
        "game_morse_runner": "Morse Runner",
        "game_morse_runner_desc": "Decode the Morse codes as fast as possible.",
        "game_morse_runner_instructions": "I'll play a Morse code. Press 1, 2 or 3 for the correct letter.",
        "game_ticking_clock": "Ticking Clocks",
        "game_ticking_clock_desc": "Find the clock that ticks differently.",
        "game_ticking_clock_instructions": "Three clocks are ticking. One of them is different. Press 1, 2 or 3 to select it.",
        "game_pitch_perfect": "Pitch Perfect",
        "game_pitch_perfect_desc": "Match your pitch to the target tone.",
        "game_pitch_perfect_instructions": "Use Up/Down arrows to change your pitch. Try to match the target tone exactly.",
        "game_mystery_door": "Mystery Doors",
        "game_mystery_door_desc": "Find the correct door based on the echo.",
        "game_mystery_door_instructions": "Three doors to choose from. Knock on them (Arrow keys) and listen to the echo. Select the door with the special sound.",
        "game_frequency_jammer": "Frequency Jammer",
        "game_frequency_jammer_desc": "Find the signal in the noise.",
        "game_frequency_jammer_instructions": "Turn the frequency dial (Left/Right) until the noise disappears and the signal becomes clear.",
        "game_stairs_of_fate": "Stairs of Fate",
        "game_stairs_of_fate_desc": "Climb the stairs without them creaking.",
        "game_stairs_of_fate_instructions": "Press Up to climb. If it creaks, jump with Space! If you walk while it creaks, you fall.",
        "game_sound_weaver": "Sound Weaver",
        "game_sound_weaver_desc": "Put the notes of the melody in the correct order.",
        "game_sound_weaver_instructions": "Listen to the melody. Reorder the notes using the arrow keys and Enter.",
        "game_beat_matcher": "Beat Matcher",
        "game_beat_matcher_desc": "Hit the rhythm perfectly.",
        "game_beat_matcher_instructions": "Press Space exactly on the beat of the kick.",
        "game_audio_balance": "Audio Balance",
        "game_audio_balance_desc": "Keep the sound centered.",
        "game_audio_balance_instructions": "The sound drifts left or right. Use arrow keys to keep it in the center.",
        "sound_creak1": "Creaking",
        "sound_metalLatch": "Metal Latch",
        "sound_cloth1": "Cloth",
        "climb_the_stairs": "Climb the stairs. Watch out for creaks!",
        "out_of_balance": "You fell out of balance!",
        "hit_perfect": "Perfect hit!",
        "miss": "Missed!",
        "beat_synced": "Perfectly synced!",
        "clock_number": "Clock {idx}",
        "select_different_clock": "Select the clock that ticks differently (1, 2, or 3).",
        "adjust_pitch_to_match": "Adjust your pitch to match the target.",
        "find_the_door_with": "Find the door with the sound: {sound}.",
        "sound_wind": "Wind",
        "sound_water": "Water",
        "sound_fire": "Fire",
        "door_number": "Door {idx}",
        "tune_to_clear_signal": "Find the clear frequency.",
        "climb_the_stairs": "Climb the stairs. Watch out for creaks!",
        "restore_the_melody": "Put the notes in the correct order.",
        "hit_the_beat": "Press Space exactly on the beat!",
        "pan_left": "To the left!",
        "pan_right": "To the right!",
        "find_the_sound": "Find the animal!",
        "radar_distance": "Distance: {dist} meters.",
        "door_echo": "Echo",
        "frequency_found": "Station found!",
        "step_safe": "Safe",
        "step_creak": "Creak!",
        "fell_down": "You fell down!",
        "hit_perfect": "Perfect!",
        "hit": "Hit!",
        "morse_a": "Letter A",
        "morse_b": "Letter B",
        "morse_c": "Letter C",
        "morse_d": "Letter D",
        "morse_e": "Letter E",
        "morse_s": "Letter S",
        "morse_o": "Letter O",
        "morse_t": "Letter T"
    }
}
